version: '2.0'
services:

  # Build the api node application and expose it on port 3001.
  api-node:
    build: ./services/external-api-node # This is where you switch to Java API
    volumes:
      - "./services/docker/volumes/node_modules-external-api-node:/usr/src/app/node_modules" # cache node_modules in local volume
      - "./services/external-api-node/app:/usr/src/app/app"
    ports:
      - "3001:3001"

#   Build the api java application and expose it on port 3002.
  api-dropwizard:
     build: ./services/external-api-dropwizard
     ports:
       - "3002:3002"